stages:
  -
    type: train_refine
    skip: True
    model:
      type:
      backbone:
        type: VGG
        cfg: '11'
        pretrain: True
      cam_head:
        type: AttentionMap
        inc: 512
        num_class: 5
      refine:
        type: SEAM
        img_c: 3
        feature1_c: 512
        feature2_c: 512
        scale: 0.3
    data:
      type:
      train:
        type: Dataset
        file_list: configs/data/train_cls.txt
        img_dir: D:/data/GID/ws/images
        ann_dir: null
        cam_dir: null
        out_dir: D:/data/GID/ws/test
        num_class: 5
        pipelines:
          -
            type: LoadImage
            bands: [0,1,2]
          -
            type: Normalize
            mean: [122.675, 116.669, 104.008]
            std: [1.0, 1.0, 1.0]
          -
            type: ToTensor
      train_loader:
        batch_size: 8
      val:
        type: Dataset
        file_list: configs/data/train_cls.txt
        img_dir: D:/data/GID/ws/images
        ann_dir: null
        cam_dir: null
        out_dir: D:/data/GID/ws/test
        num_class: 5
        pipelines:
          -
            type: LoadImage
            bands: [0,1,2]
          -
            type: Normalize
            mean: [122.675, 116.669, 104.008]
            std: [1.0, 1.0, 1.0]
          -
            type: ToTensor
      val_loader:
        batch_size: 8
    optim:
      type: SGDPolyOptimizer
      lr: 0.001
      weight_decay: 0.0005
      max_step: 3000
    runner:
      checkpoint_callback: True
      gpus: '0'
      log_gpu_memory: True
      max_steps: 3000
      logger: True
      default_root_dir: lightning_logs/seam_vgg11_test
  -
    type: infer_refine
    ckpt: lightning_logs/seam_vgg11_test/train_refine_train_refine/1639998600576_1639998600576/checkpoints/epoch=24-step=2999.ckpt
    model:
      type: pre
    data:
      type:
      test:
        type: Dataset
        file_list: configs/data/train_cls.txt
        img_dir: D:/data/GID/ws/images
        ann_dir: null
        cam_dir: null
        out_dir: D:/data/GID/ws/test
        num_class: 5
        pipelines:
          -
            type: LoadImage
            bands: [0,1,2]
          -
            type: Normalize
            mean: [122.675, 116.669, 104.008]
            std: [1.0, 1.0, 1.0]
          -
            type: ToTensor
      test_loader:
        batch_size: 8
    runner:
      gpus: '0'
      log_gpu_memory: True
      max_epochs: 1
      logger: True
      default_root_dir: lightning_logs/seam_vgg11_test